config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get 'initrax', to: 'home#initrax', as: :initrax
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    scope :users, as: :users do
      post 'pre_otp', to: 'users/sessions#pre_otp'
      get '/', to: 'users/registrations#show'
      get '/otp', to: 'users/otp#index', as: 'otp_index'
      put '/otp', to: 'users/otp#update', as: 'otp_update'
      get '/otp/qrcode', to: 'users/otp#qrcode', as: 'otp_qrcode'
      get '/otp/backup_codes', to: 'users/otp#backup_codes', as: 'otp_backup_codes'
    end
  end

  namespace :api do
    post '/characters/order', to: 'characters#order'
    post '/combatants/order', to: 'combatants#order'
    get '/combats/names', to: 'combats#names'

    resources :characters, only: %i[index show create update destroy], defaults: { format: 'json' }
    resources :combats, only: %i[index show create update destroy], defaults: { format: 'json' }
    resources :combatants, only: %i[update destroy], defaults: { format: 'json' }
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable,
         :two_factor_authenticatable, :two_factor_backupable,
         otp_secret_encryption_key: ENV['TWO_FACTOR_AUTH_SECRET'], otp_number_of_backup_codes: 12
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :homepage, format: { with: /\A#{URI.regexp.to_s}\z/ }, if: 'homepage.present?'

  has_many :characters, -> { active }
  has_many :combats, -> { active }
  has_many :combatants, -> { active }

  def to_json_ui
    {
      id: id,
      username: username,
      email: email,
      homepage: homepage,
      facebook: facebook,
      twitter: twitter,
      mastodon: mastodon,
      avatar_url: avatar_url
    }.to_json
  end

  def avatar_url
    "https://www.gravatar.com/avatar/#{Digest::MD5.new.hexdigest(email)}?s=48"
  end

  def update_without_password(params, *options)
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    # More info at:
    # https://github.com/plataformatec/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/users/otp_controller.rb
# frozen_string_literal: true

module Users
  class OtpController < ApplicationController
    before_action :authenticate_user!
    before_action :fetch_user, only: %i[index update]
    layout 'devise'

    def index
      @show_qr = session[:new_qrcode]
    end

    def update
      original_otp_status = @user.otp_required_for_login
      @user.update_attributes otp_params
      update_otp_status(original_otp_status, @user)
      redirect_to users_otp_index_path
    end

    def otp_params
      params.require(:user).permit(:otp_required_for_login)
    end

    def qrcode
      raise ActionController::RoutingError.new('Not Found') unless session[:new_qrcode]
      generated_code = generate_qrcode_for(current_user)
      send_data generated_code.as_png(
        resize_gte_to: false, resize_exactly_to: false, fill: 'white', color: 'black',
        size: 128, border_modules: 4, module_px_size: 6, file: nil
      ), filename: 'qrcode.png', type: 'image/png', disposition: 'inline'
      session[:new_qrcode] = false
    end

    def backup_codes
      return unless current_user.otp_required_for_login
      @backup_codes = current_user.generate_otp_backup_codes!
      current_user.save!
    end

    private

    def fetch_user
      @user = current_user
    end

    def generate_qrcode_for(user)
      issuer = 'Initrax'
      label = "#{issuer}:#{user.email}"
      provisioning_uri = user.otp_provisioning_uri(label, issuer: issuer)
      RQRCode::QRCode.new(provisioning_uri)
    end

    def update_otp_status(original_otp_status, user)
      if original_otp_status != user.otp_required_for_login
        if user.otp_required_for_login
          user.otp_secret = User.generate_otp_secret
          session[:new_qrcode] = true
        else
          user.otp_secret = nil
          session[:new_qrcode] = nil
        end
        user.save!
      else
        session[:new_qrcode] = nil
      end
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    def show
      redirect_to edit_user_registration_path
    end

    protected

    def update_resource(resource, params)
      resource.update_without_password(params)
    end

    def after_update_path_for(_resource)
      edit_user_registration_path
    end

    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    def pre_otp
      user = User.find_by pre_otp_params
      @otp_ok = user && user.otp_required_for_login
      respond_to do |format|
        format.js { @otp = user.current_otp if @otp_ok }
      end
    end

    private

    def pre_otp_params
      params.require(:user).permit(:email)
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/views/users/otp/_codes.html.erb
<div class="row">
  <% @backup_codes.each do |code| %>
    <div class="col-md-3 code"><%= code %></div>
  <% end %>
</div>
<div class="row">
  <p>Be sure to write these codes down or save them to a file (in a secure place). If you lose access to your device you
  you can use one of these codes to log into Initrax. Please note this is the only time this page will be displayed. If
  you click the "Generate Backup Codes" button again it will invalidate these codes and generate new ones.</p>
</div>

app/views/users/otp/backup_codes.js.erb
$('.backup-code-modal-body').html('<%= j render "/users/otp/codes" %>');

app/views/users/otp/index.html.erb
<a href="/users/edit" class="btn btn-success">Back to Settings</a>
<h3>Two-Factor Authentication</h3>
<p>Enabling this will require that you login with your e-mail address,
your password, and a one-time password provided from a device such as the <a href="https://support.google.com/accounts/answer/1066447?hl=en">Google Authenticator</a>.</p>
<%= form_for @user, url: users_otp_update_path, method: :put do |f| %>
  <div class="form-group">
    <%= f.label :otp_required_for_login, "Enable Two-Factor Authentication" %>
    <div class="radio">
      <label>
        <%= f.radio_button :otp_required_for_login, true, "data-toggle" => "collapse", "data-target" => "#save-btn-collapse#{@user.otp_required_for_login ? ".in" : ":not(.in)"}" %>
        Enabled
      </label>
    </div>
    <div class="radio">
      <label>
        <%= f.radio_button :otp_required_for_login, false, "data-toggle" => "collapse", "data-target" => "#save-btn-collapse#{@user.otp_required_for_login ? ":not(.in)" : ".in"}" %>
        Disabled
      </label>
    </div>
  </div>

  <div class="save-btn">
    <div id="save-btn-collapse" class="form-group collapse">
      <%= f.submit "Save Changes", class: "btn btn-primary" %>
    </div>
  </div>

  <% if @user.otp_required_for_login && @show_qr %>
    <div class="form-group">
      <%= image_tag '/users/otp/qrcode.png' %>
      <p></p>
      <p>Scan this code in <a href="https://support.google.com/accounts/answer/1066447?hl=en">Google Authenticator</a>
      before leaving this screen. This QR Code will not be shown again and you will NOT be able to login without using the authenticator.</p>
    </div>
  <% end %>

  <% if @user.otp_required_for_login %>
    <h3>Backup Codes</h3>
    <p>Click this button to generate backup codes that will let you login in case you lose access to your device.
    Please note that clicking the button will generate NEW codes and any previously generated codes will be invalidated.</p>

    <%= link_to "Generate Backup Codes", users_otp_backup_codes_path, :class => "btn btn-success", :remote => true, "data-toggle" => "modal", "data-target" => "#backup-code-modal" %>

    <div class="backup-codes">
      <div class="modal fade" id="backup-code-modal" title="Backup Codes" role="dialog">
        <div class="vertical-alignment-helper">
          <div class="modal-dialog vertical-align-center">
            <div class="modal-header">
              <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
              <h3 id="backupCodeModalLabel">Backup Codes</h3>
            </div>
            <div class="modal-body backup-code-modal-body">
            </div>
            <div class="modal-footer">
              <button aria-hidden="true" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>